### ISSUE TITLE
Exit Code 0

### ISSUE THREAD

**Issue by hakasapl** [comp500/Jumploader#12]
Hello,

I've been experiencing a weird issue with the 1.16.3 version of Jumploader (works fine with 1.16.2). When I press play with only jumploader installed as a mod from the twitch launcher, I get a crash message, with exit code 0, which means everything worked as expected - except it didn't?

Here's what shows up in the log, just two lines:
```
[15:58:33] [main/INFO]: ModLauncher running: args [--username, hakasapl, --version, forge-34.1.23, --gameDir, C:\Users\Hakan\Twitch\Minecraft\Instances\Beaker!, --assetsDir, C:\Users\Hakan\Twitch\Minecraft\Install\assets, --assetIndex, 1.16, --uuid, d619fbbac2da48d088f274776f095e0a, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 34.1.23, --fml.mcVersion, 1.16.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200911.084530]
[15:58:33] [main/INFO]: ModLauncher 7.0.1+78+master.e9771d8 starting: java version 1.8.0_51 by Oracle Corporation
```

Steps to Reproduce:
1. Create a new profile in twitch launcher 1.16.3, the latest Forge version.
1. Run the client normally without any mods - loads just fine with Forge (I have also tried to load jumploader directly without running with forge first, to no avail).
1. Install jumploader, launch the game, almost instantly after I press "play" in the Minecraft launcher, I get a crash message with exit code 0.

Let me know if you need more information / where I can find it because the log file isn't exactly all that descriptive.

- Hakan

**Comment by comp500** [comment]
Try using an instance name without an `!` in it? I think my parsing code might not handle escapes properly.

**Comment by hakasapl** [comment]
Easy fix. Thanks! Thanks for getting back to me so quickly, everything works fine now.

**Comment by comp500** [comment]
Looks like this is an issue in ModLauncher or Java ServiceLoader code, not Jumploader - I get the following crash with either MixinBootstrap or Jumploader (both of which use ITransformationService)

```
Exception in thread "main" java.util.ServiceConfigurationError: cpw.mods.modlauncher.api.ITransformationService: Error reading configuration file
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.parse(ServiceLoader.java:309)
	at java.util.ServiceLoader.access$200(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at cpw.mods.modlauncher.ServiceLoaderStreamUtils.errorHandlingServiceLoader(ServiceLoaderStreamUtils.java:65)
	at cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:141)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:74)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
Caused by: java.io.FileNotFoundException: C:\Users\comp500\Twitch\Minecraft\Instances\badname (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1038)
	at java.util.ServiceLoader.parse(ServiceLoader.java:304)
	... 8 more
```
