### ISSUE TITLE
Launching with Lithium causes crash

### ISSUE THREAD

**Issue by TrueCP6** [comp500/Jumploader#4]
```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 5/15/20 12:15 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access method net.minecraft.class_265.<init>(Lnet/minecraft/class_251;)V from class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube
	at me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:23)
	at net.minecraft.class_259.method_1078(class_259.java:582)
	at net.minecraft.class_259.method_1081(class_259.java:53)
	at net.minecraft.class_259.<clinit>(class_259.java:32)
	at net.minecraft.class_2248.<clinit>(class_2248.java:114)
	at net.minecraft.class_2246.<clinit>(class_2246.java:24)
	at net.minecraft.class_2378.method_10237(class_2378.java:81)
	at net.minecraft.class_2378$$Lambda$240/835631769.get(Unknown Source)
	at net.minecraft.class_2378.method_10238(class_2378.java:125)
	at net.minecraft.class_2378$$Lambda$278/1565647145.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
	at net.minecraft.class_2378.<clinit>(class_2378.java:124)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:386)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:164)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$51/1201484275.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:23)
	at net.minecraft.class_259.method_1078(class_259.java:582)
	at net.minecraft.class_259.method_1081(class_259.java:53)
	at net.minecraft.class_259.<clinit>(class_259.java:32)
	at net.minecraft.class_2248.<clinit>(class_2248.java:114)
	at net.minecraft.class_2246.<clinit>(class_2246.java:24)
	at net.minecraft.class_2378.method_10237(class_2378.java:81)
	at net.minecraft.class_2378$$Lambda$240/835631769.get(Unknown Source)
	at net.minecraft.class_2378.method_10238(class_2378.java:125)
	at net.minecraft.class_2378$$Lambda$278/1565647145.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
	at net.minecraft.class_2378.<clinit>(class_2378.java:124)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:386)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:164)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$51/1201484275.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 363639904 bytes (346 MB) / 606601216 bytes (578 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 8
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m -XX:PermSize=256m -Xss4m
	Fabric Mods: 
		amecs: Amecs 1.2.9+1.15-pre5
		appleskin: AppleSkin 1.0.8
		autoconfig1u: Auto Config v1 Updated 2.0.1
		bamboo-block-justfatlard: Bamboo Block 0.2.0
		bettermineshafts: YUNG's Better Mineshafts 0.4.1
		bowinfinityfix: Bow Infinity Fix rv8
		carpet: Carpet Mod in Fabric 1.3.19
		carpet-extra: Carpet Extra 1.3.18
		chatcalc: ChatCalc 2.1
		chunkpregen: Fabric Chunk Pregenerator 0.2.0
		cloth: Cloth Events 1.2.0
		cloth-basic-math: Cloth Basic Math 0.4.1
		cloth-config2: Cloth Config v2 2.13.2
		com_electronwill_night-config_core: core 3.5.3
		com_electronwill_night-config_toml: toml 3.5.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		dirttopath: Dirt to Path 1.3.1
		fabric: Fabric API 0.10.8+build.310-1.15
		fabric-api-base: Fabric API Base 0.1.2+28f8190f42
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+2aebb7ff0c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+045efb460c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.1.0+3e5587510c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+3e5587510c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.0+3e5587510c
		fabriccontrolling: Fabric Controlling 1.0.1
		fabricloader: Fabric Loader 0.8.3+build.196
		iamverysmart: I Am Very Smart 2.0.0+mc1.15.2
		jumploader: Jumploader 1.0.6
		lambdacontrols: LambdaControls 1.1.0
		lightoverlay: Light Overlay 4.6.1
		litematica: Litematica 0.0.0-dev.20200501.214810
		lithium: Lithium 0.4.6
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		minecraft: Minecraft 1.15.2
		ml3api: ML3API 1.3.3
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.10.2+build.32
		mousewheelie: Mouse Wheelie 1.4.5+mc1.15.2-pre1
		offlineskins: OfflineSkins 1.15.2-v2-fabric
		optifabric: Optifabric 1.0.0-beta8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.0
		org_jetbrains_annotations: annotations 17.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		phosphor: Phosphor 0.5.2+build.6
		spruceui: SpruceUI 1.3.4
		tweakeroo: Tweakeroo 0.10.0-dev.20200424.222527
		tweed: Tweed API 2.2.8
		worldedit: WorldEdit 7.1.0;8e55131
	Launched Version: forge-31.1.88
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by TrueCP6** [comment]
This only occurs for the first time when Minecraft has not been started before.

**Comment by comp500** [comment]
I haven't managed to reproduce this with just Lithium, it may be being caused by another mod. Could you try testing the same mods but without Jumploader, for example in [MultiMC](https://fabricmc.net/wiki/tutorial:install_with_multimc)?

**Comment by TheGrimdron** [comment]
Yeah, I tried it and have the same issue. It still doesn't work.

`---- Minecraft Crash Report ----
// Don't do that.

Time: 5/31/20 5:48 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access method net.minecraft.class_265.<init>(Lnet/minecraft/class_251;)V from class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube
	at me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:23)
	at net.minecraft.class_259.method_1078(class_259.java:582)
	at net.minecraft.class_259.method_1081(class_259.java:53)
	at net.minecraft.class_259.<clinit>(class_259.java:32)
	at net.minecraft.class_2248.<clinit>(class_2248.java:114)
	at net.minecraft.class_2246.<clinit>(class_2246.java:24)
	at net.minecraft.class_2378.method_10237(class_2378.java:81)
	at net.minecraft.class_2378.method_10238(class_2378.java:125)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(Unknown Source)
	at net.minecraft.class_2378.<clinit>(class_2378.java:124)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:386)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:23)
	at net.minecraft.class_259.method_1078(class_259.java:582)
	at net.minecraft.class_259.method_1081(class_259.java:53)
	at net.minecraft.class_259.<clinit>(class_259.java:32)
	at net.minecraft.class_2248.<clinit>(class_2248.java:114)
	at net.minecraft.class_2246.<clinit>(class_2246.java:24)
	at net.minecraft.class_2378.method_10237(class_2378.java:81)
	at net.minecraft.class_2378.method_10238(class_2378.java:125)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(Unknown Source)
	at net.minecraft.class_2378.<clinit>(class_2378.java:124)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:386)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3304796840 bytes (3151 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
	CPUs: 16
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 2.0.1
		bebooks: Better Enchanted Books 1.15.2-1.0.1
		blue_endless_jankson: jankson +
		carpet: Carpet Mod in Fabric 1.3.23
		chat-up: Chat Up! 1.0
		cleardespawn: Clear Despawn 1.0.4
		cloth: Cloth Events 1.2.0
		cloth-basic-math: Cloth Basic Math 0.5.0
		cloth-config2: Cloth Config v2 2.13.4
		cmdkeybind: Command Macros 1.4.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cotton-client-commands: Cotton Client Commands 0.4.2+1.14.3-SNAPSHOT
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		custom-crosshair-mod: Custom Crosshair Mod 1.0.0-fabric
		eggtab: Egg Tab 1.1.2+1.15-1.16
		elytra_swap: Elytra Swap 1.6.1-1.15
		fabric: Fabric API 0.11.1+build.312-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+2aebb7ff0c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+045efb460c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.2.1+e7a4edb30c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+3e5587510c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.0+3e5587510c
		fabricloader: Fabric Loader 0.8.5+build.199
		grid: Grid 1.15-fabric0.4.23-1.5.1
		i-need-keybinds: I Need Keybinds 0.2.1-unstable.201912010804
		iamverysmart: I Am Very Smart 2.0.0+mc1.15.2
		jankson: Jankson 2.0.1+j1.2.0
		lightoverlay: Light Overlay 4.6.1
		litematica: Litematica 0.0.0-dev.20200515.184506
		lithium: Lithium 0.4.6
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		mambience: MAmbience 1.1.0
		me_shedaniel_cloth_basic-math: basic-math 0.3.0
		minecraft: Minecraft 1.15.2
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.10.2+build.32
		nbttooltip: NBT Tooltip 1.14-1.0.3
		optifabric: Optifabric 1.0.0-beta8
		org_jetbrains_annotations: annotations 18.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		phosphor: Phosphor 0.5.2+build.6
		pling: Pling 1.1.1
		roughlyenoughitems: Roughly Enough Items 3.6.17
		roughlyenoughresources: Roughly Enough Resources 1.3.2
		screenshotclipboard: Screenshot to Clipboard 1.0.5
		shuffle: Shuffle 1.14.4-1.15.2-20w07a-1.1.1
		shulkerboxtooltip: Shulker Box Tootip 2.0.2+1.15.2
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 2.4.1
		tweakeroo: Tweakeroo 0.10.0-dev.20200424.222527
		waila: Hwyla 1.9.22
		worldeditcui: worldeditcui 1.15.2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>`

**Comment by comp500** [comment]
It's not a bug in Jumploader then, as you've replicated it without Jumploader. The common mods you have are:

```
autoconfig1u: Auto Config v1 Updated
carpet: Carpet Mod in Fabric
cloth-basic-math: Cloth Basic Math
cloth-config2: Cloth Config v2
cloth: Cloth Events
com_moandjiezana_toml_toml4j: toml4j
[... removed Fabric API components ...]
fabric: Fabric API
fabricloader: Fabric Loader
iamverysmart: I Am Very Smart
lightoverlay: Light Overlay
litematica: Litematica
lithium: Lithium
malilib: MaLiLib
minecraft: Minecraft
mm: Manningham Mills
modmenu: Mod Menu
optifabric: Optifabric
org_jetbrains_annotations: annotations
org_slf4j_slf4j-api: slf4j-api
org_slf4j_slf4j-simple: slf4j-simple
org_zeroturnaround_zt-zip: zt-zip
phosphor: Phosphor
tweakeroo: Tweakeroo
```

It's likely to be a conflict between two or more of these mods.
